# Generated by Django 3.1 on 2022-04-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ename', models.CharField(max_length=80)),
                ('ecity', models.CharField(max_length=80)),
                ('etype', models.CharField(max_length=80)),
                ('edomain', models.CharField(max_length=80)),
            ],
        ),
    ]
