# Generated by Django 3.1 on 2022-04-05 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('deptid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('deptname', models.CharField(max_length=80)),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.employee')),
            ],
        ),
    ]
